### ISSUE TITLE
How to transfer files & folders between windows and the ubuntu desktop docker?

### ISSUE THREAD

**Issue by stu-github** [mscrnt/ubuntu-desktop-docker#2]

**Comment by mscrnt** [comment]
Sorry for the late reply

There are two ways.

1. Mount a local folder to the inside of the container with the run command
`docker run -it -p 5901:5901 -p 3389:3389 -p 22:22 \
  -e USER=<USERNAME> -e PASSWORD=<PASSWORD> -e VNCPASSWORD=<VNCPASSWORD> \
  -v /path/to/local/folder:/path/inside/container \
  mscrnt/ubuntu-desktop:gpu
`

2. Transfer using docker cp
# Copy from host to container
`
docker cp /path/to/local/file.txt container_id:/path/inside/container
`
# Copy from container to host
`
docker cp container_id:/path/inside/container/file.txt /path/to/local
`
